"""Configuration loading (YAML preferred, JSON fallback) and defaults.

The committed lab config lives at config/lab.yaml and is loopback-only.
Runtime secrets (passphrase, key material) are never stored in the config;
they are generated by `hermesc2 lab init` into state/ (gitignored).
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import gating

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = PROJECT_ROOT / "config" / "lab.yaml"

DEFAULT_VALUES: dict[str, Any] = {
    "lab": {
        "listen_host": "127.0.0.1",
        "listen_port": 5555,
        "allowlist": list(gating.DEFAULT_ALLOWLIST),
        "agent_interval": 1.0,
        "jitter": 0.2,
        "session_timeout": 60.0,
        "loss_replay_timeout": 2.0,
        "safe_commands": ["date", "hostname"],
        "sandbox_root": "c2_data",
        "state_dir": "state",
        "passphrase_file": "state/lab.passphrase",
        "key_id_file": "state/lab.keyid",
        "max_session_tasks": 128,
    },
    "agent": {
        "id": "lab-node-01",
        "server_host": "127.0.0.1",
        "server_port": 5555,
        "dry_run": True,
    },
    "payloads": {
        "out_dir": "c2_data/lab_payloads",
        "max_size": 65536,
    },
    "reports": {"out_dir": "reports", "timeline_max": 5000},
}


@dataclass
class LabConfig:
    listen_host: str = "127.0.0.1"
    listen_port: int = 5555
    allowlist: list[str] = field(default_factory=lambda: list(gating.DEFAULT_ALLOWLIST))
    agent_interval: float = 1.0
    jitter: float = 0.2
    session_timeout: float = 60.0
    loss_replay_timeout: float = 2.0
    safe_commands: list[str] = field(default_factory=lambda: ["date", "hostname"])
    sandbox_root: str = "c2_data"
    state_dir: str = "state"
    passphrase_file: str = "state/lab.passphrase"
    key_id_file: str = "state/lab.keyid"
    max_session_tasks: int = 128

    @property
    def state_path(self) -> Path:
        base = Path.cwd()
        p = Path(self.state_dir)
        if not p.is_absolute():
            p = base / p
        return p

    @property
    def sandbox_path(self) -> Path:
        base = Path.cwd()
        p = Path(self.sandbox_root)
        if not p.is_absolute():
            p = base / p
        return p

    def with_overrides(self, **kw: Any) -> "LabConfig":
        # shallow attribute overrides for CLI flags (host/port only)
        d = self.__dict__.copy()
        d.update(kw)
        return LabConfig(**d)


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        import yaml  # type: ignore
    except ImportError:  # pragma: no cover - yaml always absent only in exotic envs
        raise RuntimeError("PyYAML is required to parse YAML configs (pip install PyYAML).")
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    return data if isinstance(data, dict) else {}


def load_json(path: Path) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    return data if isinstance(data, dict) else {}


def merge(base: dict, overlay: dict) -> dict:
    out = dict(base)
    for k, v in overlay.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = merge(out[k], v)
        else:
            out[k] = v
    return out


def load_config(path: str | os.PathLike | None = None) -> LabConfig:
    cfg_path = Path(path) if path else DEFAULT_CONFIG
    raw: dict[str, Any] = {"lab": {}}
    if cfg_path.exists():
        text = cfg_path.read_text(encoding="utf-8").lstrip()
        try:
            loaded = load_yaml(cfg_path) if text.startswith("{") is False else load_json(cfg_path)
        except Exception:
            loaded = load_json(cfg_path)
        raw = merge(raw, loaded)
    values = merge(DEFAULT_VALUES.get("lab", {}), raw.get("lab", {}))
    gate_host = gating.assert_loopback(values.get("listen_host", "127.0.0.1"), "listen host")
    allowlist = gating.normalize_allowlist(values.get("allowlist", gating.DEFAULT_ALLOWLIST))
    for entry in allowlist:
        if entry not in gating.DEFAULT_ALLOWLIST and entry != "lab-*":
            raise gating.ScopeViolation(
                f"Config allowlist entry {entry!r} is outside the hard-coded lab scope."
            )
    return LabConfig(
        listen_host=gate_host,
        listen_port=int(values["listen_port"]),
        allowlist=allowlist,
        agent_interval=float(values["agent_interval"]),
        jitter=float(values["jitter"]),
        session_timeout=float(values["session_timeout"]),
        loss_replay_timeout=float(values["loss_replay_timeout"]),
        safe_commands=list(values.get("safe_commands", [])),
        sandbox_root=str(values["sandbox_root"]),
        state_dir=str(values["state_dir"]),
        passphrase_file=str(values["passphrase_file"]),
        key_id_file=str(values["key_id_file"]),
        max_session_tasks=int(values["max_session_tasks"]),
    )


def save_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, sort_keys=True)
        fh.write("\n")