"""Lab-only payload generation.

Payload GEN here is strictly a lab artifact: it produces a bootstrap script
for the bundled sample agent that only ever targets 127.0.0.1 against the
committed loopback lab config. Any non-loopback --target is refused by the
safety gate. `--demo-payload` writes a tagged demo sample into the c2_data
sandbox (c2_data/lab_payloads/). Hex/poison formatting targets an OPSEC page
in the reports.
"""

from __future__ import annotations

import datetime as _dt
import json
from pathlib import Path
from typing import Optional

from . import gating
from .config import LabConfig
from .tasks import Sandbox, SandboxViolation

PAYLOAD_TAG = "# HERMES-LAB-SCOPE: loopback-only - never usable off 127.0.0.1"


def _validate_target(target: str, cfg: LabConfig) -> str:
    host = gating.validate_target(target, cfg.allowlist, what="payload target")
    # network endpoints must be loopback; lab-* names are not network endpoints
    if not gating.is_loopback(host):
        raise gating.ScopeViolation(
            f"payload target {target!r} is not a loopback endpoint; "
            "Hermes payloads are loopback-only."
        )
    return "127.0.0.1" if host != "::1" else "::1"


def bootstrap_script(
    cfg: LabConfig,
    *,
    target: str = "127.0.0.1",
    agent_id: str = "lab-stager-01",
    dry_run: bool = True,
    port: Optional[int] = None,
) -> str:
    """Return a self-contained bootstrap script string for the lab agent."""
    host = _validate_target(target, cfg)
    port = port or int(cfg.listen_port)
    if not gating.is_lab_pattern(agent_id):
        raise gating.ScopeViolation(f"agent id {agent_id!r} must match lab-*")
    overrides = {
        "listen_host": host,
        "listen_port": port,
        "state_dir": cfg.state_dir,
    }
    override_literal = repr(overrides)
    return "\n".join(
        [
            "#!/usr/bin/env python3",
            PAYLOAD_TAG,
            "# Generated by hermesc2 payload gen (lab artifacts only).",
            "# Requires the bundled sample_agent fixture and the lab runtime passphrase.",
            "import sys",
            "from hermesc2.config import load_config",
            "from hermesc2.agent import Agent",
            "from hermesc2.crypto import Crypto",
            "from hermesc2.labruntime import ensure_passphrase",
            "",
            "CFG = load_config()",
            f"_CFG_OVERRIDE = {override_literal}",
            "CFG = CFG.with_overrides(**_CFG_OVERRIDE)",
            f"dry_run = {str(bool(dry_run)).lower()}",
            f"AGENT_ID = {agent_id!r}",
            "",
            "def main():",
            "    ph = ensure_passphrase(CFG)",
            "    crypto = Crypto(ph)",
            "    agent = Agent(CFG, crypto, AGENT_ID, dry_run=dry_run,",
            "                  operator_consent=False)",
            "    print(f'[hermes] bootstrap {AGENT_ID} host={CFG.listen_host} port={CFG.listen_port}')",
            "    return agent.run_once()",
            "",
            "if __name__ == '__main__':",
            "    sys.exit(main() and 0 or 0)",
        ]
    )


def save_payload(
    cfg: LabConfig,
    *,
    target: str = "127.0.0.1",
    agent_id: str = "lab-stager-01",
    dry_run: bool = True,
    out_dir: Optional[str] = None,
) -> Path:
    """Write bootstrap to the c2_data sandbox (lab_payloads subdir)."""
    sandbox = Sandbox(cfg.sandbox_root)
    rel = "lab_payloads"
    if not (sandbox.root / rel).exists():
        (sandbox.root / rel).mkdir(parents=True, exist_ok=True)
    path = sandbox.root / rel / f"{agent_id}.py"
    if path.exists():
        return path
    script = bootstrap_script(
        cfg, target=target, agent_id=agent_id, dry_run=dry_run,
        port=int(cfg.listen_port),
    )
    path.write_text(script, encoding="utf-8")
    return path


def demo_payload(cfg: LabConfig, agent_id: str = "lab-stager-01") -> Path:
    """Generate the loopback-only demo payload in the sandbox."""
    path = save_payload(cfg, target="127.0.0.1", agent_id=agent_id, dry_run=True)
    return path


def poison_hex(data: bytes) -> str:
    """Hex-encode payload bytes for an OPSEC page (offset | hex | ascii)."""
    lines = []
    for off in range(0, len(data), 16):
        chunk = data[off : off + 16]
        hexpart = " ".join(f"{b:02x}" for b in chunk)
        asc = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append(f"{off:08x}  {hexpart:<47}  {asc}")
    return "\n".join(lines)


def opsec_page(cfg: LabConfig, data: bytes, meta: Optional[dict] = None) -> str:
    """Format a poison/hex block for a report (markdown pre block)."""
    meta = dict(meta or {})
    meta.setdefault("generated_at", _dt.datetime.now(_dt.timezone.utc).isoformat())
    meta.setdefault("scope", "loopback-only / lab-* allowlist")
    head = "```\n" + json.dumps(meta, indent=2, sort_keys=True) + "\n" + poison_hex(data) + "\n```"
    return head